= Module 2: Building the Self-Contained Appliance (v1)

[#containerfile]
== 2.1 Anatomy of a bootc Appliance Containerfile
A `Containerfile` for a `bootc` appliance defines the base OS, installed packages, and any embedded application containers. Let's review the `Containerfile` used to build our base image.

. Review the `Containerfile` for the base image:
+
[source,sh,role=execute]
----
cat Containerfile.base
----

This file specifies the RHEL 9 base image and installs MicroShift and other necessary packages.

[#physically_bound]
== 2.2 Creating "Physically-bound" Images
For air-gapped or disconnected environments, application container images can be embedded directly into the bootable OS image. This creates a "physically-bound" appliance that is fully self-contained.

We will now inspect the `Containerfile` for the `v1` image, which embeds WordPress and MySQL containers.

. Review the `Containerfile` for the `v1` image:
+
[source,sh,role=execute]
----
cat Containerfile.v1
----

This `Containerfile` uses the base image we just reviewed and adds the application container images.

[#build]
== 2.3 Hands-On: Build the Base and v1 Images
Now, you will execute the build scripts to create the bootable ISO image. These scripts use `podman` and `rhel-bootc` to build the images.

. Execute the script to build the base image:
+
[source,sh,role=execute]
----
bash -x build-base.sh
----

. Once the base build is complete, execute the script to build the `v1` image, which will produce the bootable ISO:
+
[source,sh,role=execute]
----
bash -x build.sh v1
----